//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNY2 {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MNY2.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   32비트 운영체제에선 실행할 수 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _32Bit {
            get {
                return ResourceManager.GetString("32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   맵 파일 분석중..과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Analyzing {
            get {
                return ResourceManager.GetString("Analyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기타 정보 분석중..과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Analyzing2 {
            get {
                return ResourceManager.GetString("Analyzing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클라이언트 경로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ClientPath {
            get {
                return ResourceManager.GetString("ClientPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   값 복사 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   암호화됨 (모르면 체크하세요)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Encrypted {
            get {
                return ResourceManager.GetString("Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   맵정보 나와라 얍얍!!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExtractMapinfo {
            get {
                return ResourceManager.GetString("ExtractMapinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   안쓰는 리소스 찾기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindUnused {
            get {
                return ResourceManager.GetString("FindUnused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MNY2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Inform {
            get {
                return ResourceManager.GetString("Inform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기존 맵 정보 불러오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoadMapinfo {
            get {
                return ResourceManager.GetString("LoadMapinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메모리 부족으로 인해 프로그램이 종료될 수도 있습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LowMemory {
            get {
                return ResourceManager.GetString("LowMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Map 정보 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoMapInfo {
            get {
                return ResourceManager.GetString("NoMapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mob 정보 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoMobInfo {
            get {
                return ResourceManager.GetString("NoMobInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Npc 정보 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoNpcInfo {
            get {
                return ResourceManager.GetString("NoNpcInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reactor 정보 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoReactorInfo {
            get {
                return ResourceManager.GetString("NoReactorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound 정보 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoSoundInfo {
            get {
                return ResourceManager.GetString("NoSoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   String 정보 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoStringInfo {
            get {
                return ResourceManager.GetString("NoStringInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OrderName {
            get {
                return ResourceManager.GetString("OrderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OrderSize {
            get {
                return ResourceManager.GetString("OrderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타입:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
    }
}
